src/main/java/com/dandandog/modules/blog/entity/enums/MetaType.java
package com.dandandog.modules.blog.entity.enums;

import com.dandandog.framework.common.utils.LocaleUtil;
import com.dandandog.framework.common.utils.MessageUtil;
import com.dandandog.framework.mybatis.entity.enums.BaseEnum;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * @Author: JohnnyLiu
 * @Date: 2021/9/10 10:34
 */
public enum MetaType implements BaseEnum<Integer> {

    /**
     * 分类
     */
    CATEGORY(0),

    /**
     * 标签
     */
    TAG(1);

    private final int value;


    MetaType(int value) {
        this.value = value;

    }

    @Override
    public Integer getValue() {
        return this.value;
    }

    @JsonValue
    public String getTitle() {
        return MessageUtil.getMessageEnum(this, LocaleUtil.getCurrLocale());
    }
}

src/main/webapp/resources/components/avatar.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:composite="http://java.sun.com/jsf/composite"
      xmlns:p="http://primefaces.org/ui">

<composite:interface>
    <!-- coustom attrs-->
    <composite:attribute name="user"/>

</composite:interface>

<composite:implementation>
    <p:outputPanel styleClass="p-d-flex p-ai-center">
        <p:avatar size="xlarge" styleClass="p-mr-3 ">
            <p:outputPanel rendered="#{cc.attrs.user.avatarUrl eq null}">
                <i class="ui-avatar-icon pi pi-user"/>
            </p:outputPanel>
            <p:outputPanel rendered="#{cc.attrs.user.avatarUrl ne null}">
                <p:graphicImage url="#{cc.attrs.user.avatarUrl}" styleClass="p-shadow-5"/>
            </p:outputPanel>
        </p:avatar>
        <h:outputText value="#{cc.attrs.user.username}"/>
    </p:outputPanel>

</composite:implementation>


</html>

src/main/webapp/resources/components/tags.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:composite="http://java.sun.com/jsf/composite"
      xmlns:p="http://primefaces.org/ui">

<composite:interface>
    <!-- coustom attrs-->
    <composite:attribute name="value"/>
    <composite:attribute name="type" default="enum"/>
</composite:interface>

<composite:implementation>
    <p:outputPanel rendered="#{cc.attrs.type eq 'enum'}">
        <p:tag rendered="#{cc.attrs.value.value eq 0}" value="#{cc.attrs.value.title}" styleClass="p-mr-1"
               severity="success"/>
        <p:tag rendered="#{cc.attrs.value.value eq 1}" value="#{cc.attrs.value.title}" styleClass="p-mr-1"
               severity="info"/>
        <p:tag rendered="#{cc.attrs.value.value eq 2}" value="#{cc.attrs.value.title}" styleClass="p-mr-1"
               severity="warning"/>
        <p:tag rendered="#{cc.attrs.value.value eq 3}" value="#{cc.attrs.value.title}" styleClass="p-mr-1"
               severity="danger"/>
    </p:outputPanel>

    <p:outputPanel rendered="#{cc.attrs.type eq 'bool'}">
        <p:tag rendered="#{cc.attrs.value}" value="#{msg['framework'][cc.attrs.value]}" severity="success"/>
        <p:tag rendered="#{!cc.attrs.value}" value="#{msg['framework'][cc.attrs.value]}" severity="danger"/>
    </p:outputPanel>

</composite:implementation>


</html>